// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bio-routing/tflow2/netflow/netflow.proto

package netflow

import (
	context "context"
	fmt "fmt"
	api "github.com/bio-routing/bio-rd/net/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Flow defines a network flow
type Flow struct {
	// Router flow was received from
	Router *api.IP `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	// Address family
	Family uint32 `protobuf:"varint,2,opt,name=family,proto3" json:"family,omitempty"`
	// SRC IP address
	SrcAddr *api.IP `protobuf:"bytes,3,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	// DST IP address
	DstAddr *api.IP `protobuf:"bytes,4,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	// Protocol
	Protocol uint32 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Number of packets
	Packets uint32 `protobuf:"varint,6,opt,name=packets,proto3" json:"packets,omitempty"`
	// Size of flow
	Size uint64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// SNMP interface id flow was received on
	IntIn uint32 `protobuf:"varint,8,opt,name=int_in,json=intIn,proto3" json:"int_in,omitempty"`
	// SNMP interface id flow was transmitted on
	IntOut uint32 `protobuf:"varint,9,opt,name=int_out,json=intOut,proto3" json:"int_out,omitempty"`
	// Next Hop IP address
	NextHop *api.IP `protobuf:"bytes,10,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// SRC ASN
	SrcAs uint32 `protobuf:"varint,11,opt,name=src_as,json=srcAs,proto3" json:"src_as,omitempty"`
	// DST ASN
	DstAs uint32 `protobuf:"varint,12,opt,name=dst_as,json=dstAs,proto3" json:"dst_as,omitempty"`
	// NEXT HOP ASN
	NextHopAs uint32 `protobuf:"varint,13,opt,name=next_hop_as,json=nextHopAs,proto3" json:"next_hop_as,omitempty"`
	// Unix timestamp
	Timestamp int64 `protobuf:"varint,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// SRC prefix
	SrcPfx *api.Prefix `protobuf:"bytes,15,opt,name=src_pfx,json=srcPfx,proto3" json:"src_pfx,omitempty"`
	// DST perfix
	DstPfx *api.Prefix `protobuf:"bytes,16,opt,name=dst_pfx,json=dstPfx,proto3" json:"dst_pfx,omitempty"`
	// SRC port
	SrcPort uint32 `protobuf:"varint,17,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	//DST port
	DstPort uint32 `protobuf:"varint,18,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	//Samplerate
	Samplerate           uint64   `protobuf:"varint,19,opt,name=samplerate,proto3" json:"samplerate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd7dd19847a01b50, []int{0}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetRouter() *api.IP {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Flow) GetFamily() uint32 {
	if m != nil {
		return m.Family
	}
	return 0
}

func (m *Flow) GetSrcAddr() *api.IP {
	if m != nil {
		return m.SrcAddr
	}
	return nil
}

func (m *Flow) GetDstAddr() *api.IP {
	if m != nil {
		return m.DstAddr
	}
	return nil
}

func (m *Flow) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Flow) GetPackets() uint32 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *Flow) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Flow) GetIntIn() uint32 {
	if m != nil {
		return m.IntIn
	}
	return 0
}

func (m *Flow) GetIntOut() uint32 {
	if m != nil {
		return m.IntOut
	}
	return 0
}

func (m *Flow) GetNextHop() *api.IP {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *Flow) GetSrcAs() uint32 {
	if m != nil {
		return m.SrcAs
	}
	return 0
}

func (m *Flow) GetDstAs() uint32 {
	if m != nil {
		return m.DstAs
	}
	return 0
}

func (m *Flow) GetNextHopAs() uint32 {
	if m != nil {
		return m.NextHopAs
	}
	return 0
}

func (m *Flow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Flow) GetSrcPfx() *api.Prefix {
	if m != nil {
		return m.SrcPfx
	}
	return nil
}

func (m *Flow) GetDstPfx() *api.Prefix {
	if m != nil {
		return m.DstPfx
	}
	return nil
}

func (m *Flow) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Flow) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Flow) GetSamplerate() uint64 {
	if m != nil {
		return m.Samplerate
	}
	return 0
}

// Intf groups an interfaces ID and name
type Intf struct {
	// ID is an interface ID
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is an interfaces name
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Intf) Reset()         { *m = Intf{} }
func (m *Intf) String() string { return proto.CompactTextString(m) }
func (*Intf) ProtoMessage()    {}
func (*Intf) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd7dd19847a01b50, []int{1}
}

func (m *Intf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intf.Unmarshal(m, b)
}
func (m *Intf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intf.Marshal(b, m, deterministic)
}
func (m *Intf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intf.Merge(m, src)
}
func (m *Intf) XXX_Size() int {
	return xxx_messageInfo_Intf.Size(m)
}
func (m *Intf) XXX_DiscardUnknown() {
	xxx_messageInfo_Intf.DiscardUnknown(m)
}

var xxx_messageInfo_Intf proto.InternalMessageInfo

func (m *Intf) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Flows defines a groups of flows
type Flows struct {
	// Group of flows
	Flows []*Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	// Mapping of interface names to IDs
	InterfaceMapping     []*Intf  `protobuf:"bytes,2,rep,name=interface_mapping,json=interfaceMapping,proto3" json:"interface_mapping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flows) Reset()         { *m = Flows{} }
func (m *Flows) String() string { return proto.CompactTextString(m) }
func (*Flows) ProtoMessage()    {}
func (*Flows) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd7dd19847a01b50, []int{2}
}

func (m *Flows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flows.Unmarshal(m, b)
}
func (m *Flows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flows.Marshal(b, m, deterministic)
}
func (m *Flows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flows.Merge(m, src)
}
func (m *Flows) XXX_Size() int {
	return xxx_messageInfo_Flows.Size(m)
}
func (m *Flows) XXX_DiscardUnknown() {
	xxx_messageInfo_Flows.DiscardUnknown(m)
}

var xxx_messageInfo_Flows proto.InternalMessageInfo

func (m *Flows) GetFlows() []*Flow {
	if m != nil {
		return m.Flows
	}
	return nil
}

func (m *Flows) GetInterfaceMapping() []*Intf {
	if m != nil {
		return m.InterfaceMapping
	}
	return nil
}

func init() {
	proto.RegisterType((*Flow)(nil), "netflow.Flow")
	proto.RegisterType((*Intf)(nil), "netflow.Intf")
	proto.RegisterType((*Flows)(nil), "netflow.Flows")
}

func init() {
	proto.RegisterFile("github.com/bio-routing/tflow2/netflow/netflow.proto", fileDescriptor_cd7dd19847a01b50)
}

var fileDescriptor_cd7dd19847a01b50 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4b, 0x6f, 0x13, 0x31,
	0x10, 0xc7, 0xd9, 0x74, 0xf3, 0x9a, 0x90, 0x3e, 0x8c, 0x00, 0x53, 0xa1, 0x2a, 0x4a, 0x05, 0xac,
	0x2a, 0x91, 0x48, 0xe9, 0x01, 0x89, 0x5b, 0x39, 0x20, 0x72, 0x40, 0x44, 0x7b, 0xe4, 0x12, 0x39,
	0xbb, 0xde, 0xc4, 0x22, 0x6b, 0x5b, 0xf6, 0x44, 0x0d, 0x7c, 0x45, 0xbe, 0x14, 0x1a, 0x3b, 0x09,
	0x14, 0x5a, 0x89, 0xd3, 0x7a, 0xe6, 0xff, 0x9b, 0x97, 0x3d, 0x0b, 0xd7, 0x4b, 0x85, 0xab, 0xcd,
	0x62, 0x54, 0x98, 0x7a, 0xbc, 0x50, 0xe6, 0xad, 0x33, 0x1b, 0x54, 0x7a, 0x39, 0xc6, 0x6a, 0x6d,
	0x6e, 0x27, 0x63, 0x2d, 0xc3, 0x61, 0xff, 0x1d, 0x59, 0x67, 0xd0, 0xb0, 0xf6, 0xce, 0x3c, 0x1f,
	0x3f, 0x10, 0x1d, 0xce, 0x25, 0x45, 0x8d, 0x85, 0x55, 0xf4, 0x8d, 0x91, 0xc3, 0x9f, 0x29, 0xa4,
	0x1f, 0xd7, 0xe6, 0x96, 0x5d, 0x42, 0x8b, 0x60, 0xe9, 0x78, 0x32, 0x48, 0xb2, 0xde, 0xa4, 0x37,
	0x5a, 0x28, 0x33, 0x22, 0x70, 0x3a, 0xcb, 0x77, 0x12, 0x7b, 0x06, 0xad, 0x4a, 0xd4, 0x6a, 0xfd,
	0x9d, 0x37, 0x06, 0x49, 0xd6, 0xcf, 0x77, 0x16, 0x7b, 0x0d, 0x1d, 0xef, 0x8a, 0xb9, 0x28, 0x4b,
	0xc7, 0x8f, 0xfe, 0x0d, 0x6f, 0x7b, 0x57, 0xdc, 0x94, 0xa5, 0x23, 0xae, 0xf4, 0x18, 0xb9, 0xf4,
	0x1e, 0xae, 0xf4, 0x18, 0xb8, 0x73, 0xe8, 0x84, 0xf6, 0x0a, 0xb3, 0xe6, 0xcd, 0x50, 0xe9, 0x60,
	0x33, 0x0e, 0x6d, 0x2b, 0x8a, 0x6f, 0x12, 0x3d, 0x6f, 0x05, 0x69, 0x6f, 0x32, 0x06, 0xa9, 0x57,
	0x3f, 0x24, 0x6f, 0x0f, 0x92, 0x2c, 0xcd, 0xc3, 0x99, 0x3d, 0x85, 0x96, 0xd2, 0x38, 0x57, 0x9a,
	0x77, 0x02, 0xdc, 0x54, 0x1a, 0xa7, 0x9a, 0x3d, 0x87, 0x36, 0xb9, 0xcd, 0x06, 0x79, 0x37, 0x4e,
	0xa2, 0x34, 0x7e, 0xd9, 0x20, 0x75, 0xa8, 0xe5, 0x16, 0xe7, 0x2b, 0x63, 0x39, 0xdc, 0xd3, 0x21,
	0x89, 0x9f, 0x8c, 0xa5, 0xbc, 0x61, 0x62, 0xcf, 0x7b, 0x31, 0x2f, 0x8d, 0xe8, 0xc9, 0x1d, 0x06,
	0xf4, 0xfc, 0x71, 0x74, 0xd3, 0x44, 0x9e, 0x5d, 0x40, 0x6f, 0x9f, 0x95, 0xb4, 0x7e, 0xd0, 0xba,
	0xbb, 0x5c, 0x37, 0x9e, 0xbd, 0x84, 0x2e, 0xaa, 0x5a, 0x7a, 0x14, 0xb5, 0xe5, 0xc7, 0x83, 0x24,
	0x3b, 0xca, 0x7f, 0x3b, 0x58, 0x06, 0x74, 0x81, 0x73, 0x5b, 0x6d, 0xf9, 0x49, 0x68, 0xe9, 0xe4,
	0xd0, 0xd2, 0xcc, 0xc9, 0x4a, 0x6d, 0x73, 0xea, 0x65, 0x56, 0x6d, 0x89, 0xa4, 0xf2, 0x44, 0x9e,
	0x3e, 0x40, 0x96, 0x1e, 0x89, 0x7c, 0x11, 0x5f, 0xcc, 0x1a, 0x87, 0xfc, 0x2c, 0x5e, 0x23, 0xe5,
	0x30, 0x0e, 0x49, 0x0a, 0x49, 0x48, 0x62, 0x51, 0xa2, 0x20, 0x92, 0x2e, 0x00, 0xbc, 0xa8, 0xed,
	0x5a, 0x3a, 0x81, 0x92, 0x3f, 0x09, 0xf7, 0xfc, 0x87, 0x67, 0x78, 0x05, 0xe9, 0x54, 0x63, 0xc5,
	0x8e, 0xa1, 0xa1, 0xca, 0xb0, 0x48, 0xfd, 0xbc, 0xa1, 0x4a, 0x7a, 0x19, 0x2d, 0x6a, 0x19, 0xb6,
	0xa6, 0x9b, 0x87, 0xf3, 0x70, 0x05, 0x4d, 0x5a, 0x3c, 0xcf, 0x2e, 0xa1, 0x49, 0xbb, 0xeb, 0x79,
	0x32, 0x38, 0xca, 0x7a, 0x93, 0xfe, 0x68, 0xbf, 0xdb, 0x24, 0xe7, 0x51, 0x63, 0xef, 0xe1, 0x4c,
	0x69, 0x94, 0xae, 0x12, 0x85, 0x9c, 0xd7, 0xc2, 0x5a, 0xa5, 0x97, 0xbc, 0xf1, 0x57, 0x00, 0xd5,
	0xce, 0x4f, 0x0f, 0xdc, 0xe7, 0x88, 0x4d, 0xde, 0x41, 0x57, 0x68, 0x6d, 0x50, 0xa0, 0x71, 0xec,
	0x0a, 0x3a, 0x37, 0xd1, 0x90, 0xec, 0x6e, 0xa9, 0xf3, 0xbb, 0xe6, 0xf0, 0xd1, 0x87, 0x37, 0x5f,
	0x5f, 0xfd, 0xd7, 0xdf, 0xb8, 0x68, 0x85, 0xed, 0xbc, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x78,
	0xe6, 0xff, 0xe8, 0xbd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnnotatorClient is the client API for Annotator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnnotatorClient interface {
	Annotate(ctx context.Context, in *Flow, opts ...grpc.CallOption) (*Flow, error)
}

type annotatorClient struct {
	cc *grpc.ClientConn
}

func NewAnnotatorClient(cc *grpc.ClientConn) AnnotatorClient {
	return &annotatorClient{cc}
}

func (c *annotatorClient) Annotate(ctx context.Context, in *Flow, opts ...grpc.CallOption) (*Flow, error) {
	out := new(Flow)
	err := c.cc.Invoke(ctx, "/netflow.annotator/Annotate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnotatorServer is the server API for Annotator service.
type AnnotatorServer interface {
	Annotate(context.Context, *Flow) (*Flow, error)
}

func RegisterAnnotatorServer(s *grpc.Server, srv AnnotatorServer) {
	s.RegisterService(&_Annotator_serviceDesc, srv)
}

func _Annotator_Annotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnotatorServer).Annotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netflow.annotator/Annotate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnotatorServer).Annotate(ctx, req.(*Flow))
	}
	return interceptor(ctx, in, info, handler)
}

var _Annotator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "netflow.annotator",
	HandlerType: (*AnnotatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Annotate",
			Handler:    _Annotator_Annotate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/bio-routing/tflow2/netflow/netflow.proto",
}
